---

- name: Install golang
  include: golang.yml

- include_vars: golang.yml

- name: Create /var/run/netns dir
  file: path=/var/run/netns state=directory

- name: Download cni repo
  git:
  args:
    repo: "https://github.com/containernetworking/cni.git"
    dest: "{{ go_gopath }}/src/cni"
    force: yes

- name: Build cni plugins
  shell: . {{ go_profile_entry }}; ./build
  args:
    chdir: "{{ go_gopath }}/src/cni"

- name: Download cni-opencontrail-plugin repo
  git:
  args:
    repo: "https://github.com/codilime/cni-opencontrail-plugin.git"
    dest: "{{ go_gopath }}/src/cni-opencontrail-plugin"
    force: yes
    version: master

- name: Build cni-opencontrail-plugin
  shell: . {{ go_profile_entry }}; go get && go build cni-opencontrail-plugin.go
  args:
    chdir: "{{ go_gopath }}/src/cni-opencontrail-plugin"

- name: Create cni dirs
  file:
  args:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{mesos_cni_config_dir}}"
    - "{{mesos_cni_plugins_dir}}"
  tags:
    - cni-configs

- name: Install plugins
  shell: mv "{{ item }}" "{{ mesos_cni_plugins_dir }}"
  with_items:
    - "{{ go_gopath }}/src/cni/bin/bridge"
    - "{{ go_gopath }}/src/cni/bin/host-local"
    - "{{ go_gopath }}/src/cni-opencontrail-plugin/cni-opencontrail-plugin"

- name: Install contrail_cli
  shell: mv "{{ item }}" "/"
  with_items:
    - "{{ go_gopath }}/src/cni-opencontrail-plugin/contrail_cli.py"

- name: Copy cni configs
  template:
  args:
    src: "{{ item }}.j2"
    dest: "{{ mesos_cni_config_dir }}/{{ item }}"
  with_items:
    - cni-opencontrail-plugin.conf
    - cni-bridge-plugin.conf
  tags:
    - cni-configs

- name: Restart mesos-slave
  service: name=mesos-slave state=restarted
  tags:
    - cni-configs
