---

- name: Make sure necessary packages are installed
  become: yes
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ package }}"
    state: latest
    force: yes
    update_cache: yes
  with_items:
    - python-netaddr
    - python-dev
    - python-markupsafe
    - build-essential
    - libssl-dev
    - libffi-dev
  loop_control:
    loop_var: package
  retries: 3
  delay: 5
  register: result
  until: result|success
