---
- name: Install Keystone and requirement packages
  action: apt name={{ item }} update_cache=yes cache_valid_time=3600 state=latest
  become: yes
  with_items:
    - ubuntu-cloud-keyring
    - keystone
    - python-keystoneclient
  retries: 3
  delay: 5
  register: result
  until: result|success

- name: Start Keystone
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: keystone

- name: install script for cron job to periodically flush expired tokens
  become: yes
  copy:
    content: "#!/bin/sh\n/usr/bin/keystone-manage token_flush\n"
    dest: /etc/cron.daily/keystone-token-flush
    owner: root
    group: root
    mode: 0755
