---
- name: wait until keystone service is ready
  wait_for:
    delay: 1
    host: "{{ openstack_identity_endpoint_host }}"
    port: 35357
    state: started

- name: ensure admin tenant has been created
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    tenant_description: "Admin Tenant"

- name: ensure admin user has been created
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    password: "{{ openstack_identity_admin_password }}"

- name: ensure admin role has been created and associated with admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: admin

- name: ensure _member_ role has been created and associated with admin user
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: admin
    user: admin
    role: _member_

- name: ensure service tenant has been created
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: service
    tenant_description: "Service Tenant"

# This module (keystone_service) is taken directly from: https://github.com/openstack-ansible/openstack-ansible-modules (revision: 49cab146d9a66ead14ff45483e5de7a72617d8f0)
- name: endpoint creation
  environment:
    http_proxy: ''
    HTTP_PROXY: ''
  keystone_service:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    region: "{{ openstack_identity_region }}"
    name: keystone
    type: identity
    description: "Identity Service"
    public_url: "{{ openstack_identity_public_url }}"
    internal_url: "{{ openstack_identity_internal_url }}"
    admin_url: "{{ openstack_identity_admin_url }}"
    state: present

- name: update admin.openrc from template
  template:
    src: templates/admin.openrc
    dest: "~/admin.openrc"
    owner: "{{ ansible_ssh_user }}"

- name: create demo tenant
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: demo
    tenant_description: "Demo Tenant"

- name: create demo user
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: demo
    user: demo
    password: "{{ openstack_identity_demo_password }}"

- name: associate _member_ role with demo user
  keystone_user:
    endpoint: "{{ openstack_identity_admin_url }}"
    token: "{{ openstack_identity_admin_token }}"
    tenant: demo
    user: demo
    role: _member_

- name: update demo.openrc from template
  template:
    src: templates/demo.openrc
    dest: "~/demo.openrc"
    owner: "{{ ansible_ssh_user }}"

