---
- name: ensure git exists
  become: yes
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: git
    state: latest
  delegate_to: 127.0.0.1
  run_once: true
 
# Uncomment this to update openstack library
#- name: check out library needed for demo deployment from github.com
#  delegate_to: 127.0.0.1
#  git:
#    repo:
#      'https://github.com/openstack-ansible/openstack-ansible-modules.git'
#    dest: library/openstack-ansible-modules
#    update: yes
#  run_once: true
#
#- name: copy keystone modules to library
#  delegate_to: 127.0.0.1
#  copy: src=library/openstack-ansible-modules/keystone_service dest=library/keystone_service
#  run_once: true

- include: mysql.yml
- include: install.yml
- include: configure.yml
- include: keystone.yml
