---
- name: MySQL | Set debconf vars
  become: yes
  shell: echo mysql-server mysql-server/root_password password {{ mysql_root_password }} | /usr/bin/debconf-set-selections
  tags: mysql

- name: MySQL | Set debconf vars
  become: yes
  shell: echo mysql-server mysql-server/root_password_again password {{ mysql_root_password }} | /usr/bin/debconf-set-selections
  tags: mysql

- name: Install MySQL
  become: yes
  action: apt name={{ item }} update_cache=yes cache_valid_time=3600 state=present
  with_items:
    - mysql-server-5.6
    - mysql-client-5.6
    - python-mysqldb
    - libmysqlclient-dev
  retries: 3
  delay: 5
  register: result
  until: result|success

#- name: copy cnf
#  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
#  become: yes

- name: Start the MySQL service
  become: yes
  service:
    name: mysql
    state: started
    enabled: true

- name: update mysql root password for all root accounts
  become: yes
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
